name: "ESLint check"
on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-yarn.lock') }}

      - name: Install modules
        run: pnpm install

      - name: Lint
        run: pnpm run lint
